services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    networks:
      - proxy

networks:
  proxy:
    external: true