services:
  traefik:
    image: traefik:v2.10
    container_name: traefik

    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # redirección HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # solo file provider
      - "--providers.file.filename=/etc/traefik/dynamic.yml"

      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro

    networks:
      - proxy

networks:
  proxy:
    external: true