http:
  routers:
    web:
      rule: "Host(`app.midominio.com`)"
      entryPoints:
        - websecure
      service: web-service
      tls: {}

    mailhog:
      rule: "Host(`mail.midominio.com`)"
      entryPoints:
        - websecure
      service: mailhog-service
      tls: {}

    portainer:
      rule: "Host(`portainer.midominio.com`)"
      entryPoints:
        - websecure
      service: portainer-service
      tls: {}

    adminer:
      rule: "Host(`adminer.midominio.com`)"
      entryPoints:
        - websecure
      service: adminer-service
      tls: {}

    phpmyadmin:
      rule: "Host(`phpmyadmin.midominio.com`)"
      entryPoints:
        - websecure
      service: phpmyadmin-service
      tls: {}

    wordpress:
      rule: "Host(`blog.midominio.com`)"
      entryPoints:
        - websecure
      service: wordpress-service
      tls: {}

    dashboard:
      rule: "Host(`dashboard.midominio.com`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: {}

  services:
    web-service:
      loadBalancer:
        servers:
          - url: "http://web1:80"
          - url: "http://web2:80"
          - url: "http://web3:80"

    mailhog-service:
      loadBalancer:
        servers:
          - url: "http://mailhog:8025"

    portainer-service:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    adminer-service:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

    phpmyadmin-service:
      loadBalancer:
        servers:
          - url: "http://phpmyadmin:80"

    wordpress-service:
      loadBalancer:
        servers:
          - url: "http://wordpress:80"

tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem