services:
  web:
    image: nginx:latest
    container_name: web

    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`app.midominio.com`)"
      - "traefik.http.routers.web.entrypoints=web"


    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

    networks:
      - proxy

networks:
  proxy:
    external: true