services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: laboratorio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - proxy

volumes:
  postgres_data:

networks:
  proxy:
    external: true